name: Start Code Review
on:
  workflow_dispatch

jobs:
  create-pr-on-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@1.0.0

    - name: Create pull request
      uses: thomaseizinger/create-pull-request@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        head: feature/midterm
        base: main
        title: "Adds KK's favorite recipe"
        body: "This pull request adds the content and mobile styles for KK's favorite recipe for the Your Favorite Recipe assignment. I did my first round of HTML and CSS, but I have two things I can't figure out. One is that all my text is really large in the beginning, from my title to "Ingredients", but I didn't add any CSS to it, so I don't understand why it's all so large. And in my last two pictures, I got them to show up side by side, but I can't get the blue background to go all the way down underneath the photos. Can you look through my code and help me figure out what's going on? What am I missing? Is there anything I could improve?"